# Generated by Django 5.2.15 on 2026-07-09 19:58

import django.db.models.deletion
import django.utils.timezone
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0002_consenttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_reference', models.CharField(default=reports.models.generate_report_reference, max_length=40, unique=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_type', models.CharField(choices=[('applicant_onboarding', 'Applicant onboarding')], default='applicant_onboarding', max_length=40)),
                ('file', models.FileField(blank=True, upload_to=reports.models.report_file_path)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('failed', 'Failed')], default='generated', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_records', to='applicants.applicant')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
