# Generated by Django 5.2.15 on 2026-07-03 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('business_type', models.CharField(choices=[('real_estate', 'Real Estate'), ('cooperative', 'Cooperative / Loans'), ('hr', 'HR / Recruitment'), ('school', 'School / Training'), ('sme', 'SME'), ('other', 'Other')], default='sme', max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Default onboarding link', max_length=120)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('applicant_type_default', models.CharField(default='customer', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_links', to='organizations.organization')),
            ],
        ),
    ]
