# Generated by Django 5.2.15 on 2026-07-03 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mock', max_length=80)),
                ('verification_type', models.CharField(choices=[('nin', 'NIN'), ('bvn', 'BVN'), ('face_match', 'Face Match'), ('document_check', 'Document Check')], max_length=40)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('error', 'Error')], default='not_started', max_length=30)),
                ('request_reference', models.CharField(blank=True, max_length=120)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='applicants.applicant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
