# Generated by Django 5.2.15 on 2026-07-03 23:02

import django.db.models.deletion
import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_card', 'ID Card'), ('nin_slip', 'NIN Slip'), ('passport', 'Passport'), ('utility_bill', 'Utility Bill'), ('selfie', 'Selfie'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(upload_to=documents.models.applicant_document_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicants.applicant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
