import hashlib
from io import BytesIO
from pathlib import Path
from xml.sax.saxutils import escape

from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from audit.models import AuditLog
from verification.providers import sanitize_response_summary

from .models import ReportRecord

PAGE_WIDTH, PAGE_HEIGHT = A4


def clean_text(value, fallback="N/A"):
    if value is None or value == "":
        return fallback
    return escape(str(value))


def paragraph(value, style):
    return Paragraph(clean_text(value), style)


def human_datetime(value):
    if not value:
        return "N/A"
    return timezone.localtime(value).strftime("%Y-%m-%d %H:%M")


def summarize_payload(value):
    sanitized = sanitize_response_summary(value or {})
    if isinstance(sanitized, dict):
        pairs = []
        for key, item in sanitized.items():
            if isinstance(item, (dict, list, tuple)):
                item = "[summary available]"
            pairs.append(f"{key}: {item}")
        return "; ".join(pairs)[:180] or "No summary"
    return str(sanitized)[:180] or "No summary"


def applicant_report_filename(applicant, generated_at=None):
    generated_at = generated_at or timezone.now()
    applicant_name = "-".join(Path(applicant.full_name.lower()).name.split()) or "applicant"
    safe_name = "".join(char for char in applicant_name if char.isalnum() or char == "-").strip("-") or "applicant"
    return f"verifyflow-{applicant.organization.slug}-{safe_name}-{generated_at:%Y%m%d}.pdf"


class NumberedCanvas:
    def __init__(self, canvas_obj, report_record, show_mock_watermark):
        self.canvas = canvas_obj
        self.report_record = report_record
        self.show_mock_watermark = show_mock_watermark

    def draw_page(self, doc):
        canvas = self.canvas
        canvas.saveState()
        if self.show_mock_watermark:
            canvas.setFont("Helvetica-Bold", 32)
            canvas.setFillColor(colors.Color(0.8, 0.2, 0.2, alpha=0.10))
            canvas.translate(PAGE_WIDTH / 2, PAGE_HEIGHT / 2)
            canvas.rotate(35)
            canvas.drawCentredString(0, 0, "Demo / Not Government Verification")
            canvas.rotate(-35)
            canvas.translate(-PAGE_WIDTH / 2, -PAGE_HEIGHT / 2)
        canvas.setFillColor(colors.HexColor("#102033"))
        canvas.rect(0, PAGE_HEIGHT - 0.42 * inch, PAGE_WIDTH, 0.42 * inch, fill=1, stroke=0)
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 10)
        canvas.drawString(0.65 * inch, PAGE_HEIGHT - 0.27 * inch, "VerifyFlow NG Verification Report")
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(PAGE_WIDTH - 0.65 * inch, PAGE_HEIGHT - 0.27 * inch, self.report_record.report_reference)
        canvas.setFillColor(colors.HexColor("#64748b"))
        canvas.drawString(0.65 * inch, 0.42 * inch, "Generated by VerifyFlow NG")
        canvas.drawRightString(PAGE_WIDTH - 0.65 * inch, 0.42 * inch, f"Page {doc.page}")
        canvas.restoreState()


def draw_logo_or_mark(canvas, organization):
    logo = getattr(organization, "logo", None)
    if logo:
        try:
            canvas.drawImage(logo.path, 0.75 * inch, PAGE_HEIGHT - 1.75 * inch, width=1.0 * inch, height=1.0 * inch, preserveAspectRatio=True, mask="auto")
            return
        except (OSError, ValueError):
            pass
    canvas.setFillColor(colors.HexColor("#0f766e"))
    canvas.roundRect(0.75 * inch, PAGE_HEIGHT - 1.75 * inch, 0.85 * inch, 0.85 * inch, 6, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 24)
    canvas.drawCentredString(1.175 * inch, PAGE_HEIGHT - 1.45 * inch, "V")


def build_table(rows, styles):
    table = Table(rows, colWidths=[1.9 * inch, 4.55 * inch], hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#475569")),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#dbe3ef")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return table


def section_title(title, story, styles):
    story.append(Spacer(1, 0.18 * inch))
    story.append(Paragraph(clean_text(title), styles["SectionTitle"]))
    story.append(Spacer(1, 0.07 * inch))


def add_key_value_section(story, title, rows, styles):
    section_title(title, story, styles)
    story.append(build_table([[paragraph(label, styles["TableLabel"]), paragraph(value, styles["TableBody"])] for label, value in rows], styles))


def collect_audit_entries(applicant):
    entity_ids = {str(applicant.id)}
    entity_ids.update(str(document.id) for document in applicant.documents.all())
    entity_ids.update(str(verification.id) for verification in applicant.verification_requests.all())
    return AuditLog.objects.filter(organization=applicant.organization, entity_id__in=entity_ids)[:8]


def build_applicant_report_pdf(report_record):
    applicant = report_record.applicant
    generated_at = report_record.generated_at
    show_mock_watermark = applicant.verification_requests.filter(provider="mock").exists()
    buffer = BytesIO()
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="TitleCenter", parent=styles["Title"], alignment=TA_CENTER, textColor=colors.HexColor("#102033"), fontSize=22, leading=26))
    styles.add(ParagraphStyle(name="MetaCenter", parent=styles["Normal"], alignment=TA_CENTER, textColor=colors.HexColor("#64748b"), fontSize=9, leading=13))
    styles.add(ParagraphStyle(name="SectionTitle", parent=styles["Heading2"], textColor=colors.HexColor("#0f766e"), fontSize=13, leading=16, spaceAfter=4))
    styles.add(ParagraphStyle(name="TableLabel", parent=styles["Normal"], textColor=colors.HexColor("#475569"), fontSize=8, leading=11))
    styles.add(ParagraphStyle(name="TableBody", parent=styles["Normal"], textColor=colors.HexColor("#172033"), fontSize=8.5, leading=12))
    styles.add(ParagraphStyle(name="RightSmall", parent=styles["Normal"], alignment=TA_RIGHT, textColor=colors.HexColor("#64748b"), fontSize=8, leading=10))

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.65 * inch,
        leftMargin=0.65 * inch,
        topMargin=0.72 * inch,
        bottomMargin=0.72 * inch,
        pageCompression=0,
    )
    story = []

    title_rows = [
        ["Report ID", report_record.report_reference],
        ["Generated at", human_datetime(generated_at)],
        ["Organization", applicant.organization.name],
        ["Applicant status", applicant.get_status_display()],
        ["Report type", report_record.get_report_type_display()],
    ]
    story.append(Spacer(1, 0.95 * inch))
    story.append(Paragraph("VerifyFlow NG Applicant Verification Report", styles["TitleCenter"]))
    story.append(Paragraph("Professional onboarding and compliance evidence summary", styles["MetaCenter"]))
    story.append(Spacer(1, 0.35 * inch))
    story.append(build_table([[paragraph(label, styles["TableLabel"]), paragraph(value, styles["TableBody"])] for label, value in title_rows], styles))
    if show_mock_watermark:
        story.append(Spacer(1, 0.22 * inch))
        story.append(Paragraph("Demo / Not Government Verification", styles["MetaCenter"]))
    story.append(PageBreak())

    add_key_value_section(story, "Applicant Identity Summary", [
        ("Full name", applicant.full_name),
        ("Applicant type", applicant.get_applicant_type_display()),
        ("Masked NIN", applicant.nin_masked or "N/A"),
        ("Masked BVN", applicant.bvn_masked or "N/A"),
        ("Date of birth", applicant.date_of_birth or "N/A"),
        ("Gender", applicant.get_gender_display() or "N/A"),
        ("Submitted at", human_datetime(applicant.submitted_at)),
    ], styles)

    add_key_value_section(story, "Contact Details", [
        ("Phone", applicant.phone),
        ("Email", applicant.email or "N/A"),
        ("Address", applicant.address or "N/A"),
    ], styles)

    add_key_value_section(story, "Guarantor / Next-of-Kin Details", [
        ("Name", applicant.guarantor_name or "N/A"),
        ("Phone", applicant.guarantor_phone or "N/A"),
        ("Relationship", applicant.guarantor_relationship or "N/A"),
    ], styles)

    consent = getattr(applicant, "consent", None)
    add_key_value_section(story, "Consent Evidence", [
        ("Accepted", "Yes" if getattr(consent, "accepted", False) else "No"),
        ("Accepted at", human_datetime(getattr(consent, "accepted_at", None))),
        ("Consent version", getattr(consent, "consent_version", "N/A")),
        ("Consent text", getattr(consent, "consent_text", "No consent record found.")),
    ], styles)

    document_rows = []
    for document in applicant.documents.all():
        document_rows.append([
            paragraph(document.get_document_type_display(), styles["TableBody"]),
            paragraph(document.original_filename or "Stored document", styles["TableBody"]),
            paragraph(document.get_review_status_display(), styles["TableBody"]),
            paragraph(document.review_note or "No review note", styles["TableBody"]),
        ])
    section_title("Document Checklist and Review Results", story, styles)
    if document_rows:
        documents_table = Table([[paragraph("Category", styles["TableLabel"]), paragraph("Filename", styles["TableLabel"]), paragraph("Review", styles["TableLabel"]), paragraph("Note", styles["TableLabel"])]] + document_rows, colWidths=[1.25 * inch, 1.8 * inch, 1.1 * inch, 2.3 * inch], hAlign="LEFT")
        documents_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#dbe3ef")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(documents_table)
    else:
        story.append(Paragraph("No uploaded documents recorded.", styles["TableBody"]))

    verification_rows = []
    for verification in applicant.verification_requests.all():
        verification_rows.append([
            paragraph(verification.get_verification_type_display(), styles["TableBody"]),
            paragraph(verification.provider, styles["TableBody"]),
            paragraph(verification.get_status_display(), styles["TableBody"]),
            paragraph(summarize_payload(verification.response_summary), styles["TableBody"]),
            paragraph(human_datetime(verification.created_at), styles["TableBody"]),
        ])
    section_title("Verification History", story, styles)
    if verification_rows:
        verification_table = Table([[paragraph("Type", styles["TableLabel"]), paragraph("Provider", styles["TableLabel"]), paragraph("Status", styles["TableLabel"]), paragraph("Summary", styles["TableLabel"]), paragraph("Date", styles["TableLabel"])]] + verification_rows, colWidths=[1.1 * inch, 0.9 * inch, 0.85 * inch, 2.45 * inch, 1.15 * inch], hAlign="LEFT")
        verification_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#dbe3ef")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(verification_table)
    else:
        story.append(Paragraph("No verification requests recorded.", styles["TableBody"]))

    review_rows = []
    for review in applicant.reviews.all():
        review_rows.append((human_datetime(review.reviewed_at), review.reviewer or "N/A", review.get_status_display(), review.note or "No note"))
    add_key_value_section(story, "Reviewer Notes", [
        (f"{reviewed_at} - {status}", f"{reviewer}: {note}") for reviewed_at, reviewer, status, note in review_rows
    ] or [("Review history", "No reviewer notes recorded.")], styles)

    audit_rows = []
    for entry in collect_audit_entries(applicant):
        audit_rows.append((human_datetime(entry.created_at), entry.actor or "System", entry.action))
    add_key_value_section(story, "Audit Summary", [
        (f"{created_at} - {actor}", action) for created_at, actor, action in audit_rows
    ] or [("Audit trail", "No audit events recorded for this applicant.")], styles)

    def first_page(canvas, doc):
        NumberedCanvas(canvas, report_record, show_mock_watermark).draw_page(doc)
        draw_logo_or_mark(canvas, applicant.organization)

    def later_pages(canvas, doc):
        NumberedCanvas(canvas, report_record, show_mock_watermark).draw_page(doc)

    doc.build(story, onFirstPage=first_page, onLaterPages=later_pages)
    pdf_bytes = buffer.getvalue()
    buffer.seek(0)
    return buffer, hashlib.sha256(pdf_bytes).hexdigest()


def generate_applicant_report(applicant, generated_by):
    report_record = ReportRecord.objects.create(applicant=applicant, generated_by=generated_by)
    try:
        pdf_buffer, checksum = build_applicant_report_pdf(report_record)
    except Exception:
        report_record.status = ReportRecord.Statuses.FAILED
        report_record.save(update_fields=["status"])
        raise
    report_record.checksum_sha256 = checksum
    report_record.status = ReportRecord.Statuses.GENERATED
    report_record.save(update_fields=["checksum_sha256", "status"])
    return report_record, pdf_buffer
